model_list:
  - model_name: modelo-llama3.1
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: http://localhost:11434
  - model_name: modelo-gemma4
    litellm_params:
      model: ollama/gemma4:e4b
      api_base: http://localhost:11434
  - model_name: modelo-deepseek-r1
    litellm_params:
      model: ollama/deepseek-r1:8b
      api_base: http://localhost:11434
  - model_name: modelo-deepseek-v4-flash
    litellm_params:
      model: ollama/deepseek-v4-flash-stock:latest
      api_base: http://localhost:11434
  - model_name: modelo-qwen3.5
    litellm_params:
      model: ollama/qwen3.5:9b
      api_base: http://localhost:11434
